spring:
  dataSource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/demo?serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    port: 6379
    host: localhost
    database: 0
    #?serverTimezone=GMT%2B8
server:
  port: 80
  #日志记录级别debug
logging:
  level:
    com.itmuma: debug
    org.springframework: info
mybatis:
  type-aliases-package: com.itmuma.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true